#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class Guardia_Medicos_Funcione
	{
		private int IdMedico1;
		public virtual int IdMedico
		{
			get
			{
				return this.IdMedico1;
			}
			set
			{
				this.IdMedico1 = value;
			}
		}
		
		private string IdFuncion1;
		public virtual string IdFuncion
		{
			get
			{
				return this.IdFuncion1;
			}
			set
			{
				this.IdFuncion1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
