#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class sp_SSO_AllowedAppsByEfectorResultSet0
	{
		private int _idAplicacion;
		public virtual int idAplicacion
		{
			get
			{
				return this._idAplicacion;
			}
			set
			{
				this._idAplicacion = value;
			}
		}
		
		private string _name;
		public virtual string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _executable;
		public virtual string executable
		{
			get
			{
				return this._executable;
			}
			set
			{
				this._executable = value;
			}
		}
		
		private string _url;
		public virtual string url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		
		private string _image;
		public virtual string image
		{
			get
			{
				return this._image;
			}
			set
			{
				this._image = value;
			}
		}
		
		private string _urlPage;
		public virtual string urlPage
		{
			get
			{
				return this._urlPage;
			}
			set
			{
				this._urlPage = value;
			}
		}
		
		private bool? _hasViews;
		public virtual bool? hasViews
		{
			get
			{
				return this._hasViews;
			}
			set
			{
				this._hasViews = value;
			}
		}
		
		private bool? _hasAlarms;
		public virtual bool? hasAlarms
		{
			get
			{
				return this._hasAlarms;
			}
			set
			{
				this._hasAlarms = value;
			}
		}
		
		private bool? _hasProtectedModules;
		public virtual bool? hasProtectedModules
		{
			get
			{
				return this._hasProtectedModules;
			}
			set
			{
				this._hasProtectedModules = value;
			}
		}
		
		private bool _intefase_Visible;
		public virtual bool intefase_visible
		{
			get
			{
				return this._intefase_Visible;
			}
			set
			{
				this._intefase_Visible = value;
			}
		}
		
		private string _version;
		public virtual string version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		
	}
}
#pragma warning restore 1591
