#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class SSO_RoleGroup
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private bool AutomaticName1;
		public virtual bool AutomaticName
		{
			get
			{
				return this.AutomaticName1;
			}
			set
			{
				this.AutomaticName1 = value;
			}
		}
		
		private int? IdPerfil1;
		public virtual int? IdPerfil
		{
			get
			{
				return this.IdPerfil1;
			}
			set
			{
				this.IdPerfil1 = value;
			}
		}
		
		private int? IdEfector1;
		public virtual int? IdEfector
		{
			get
			{
				return this.IdEfector1;
			}
			set
			{
				this.IdEfector1 = value;
			}
		}
		
		private int? IdAplicacion1;
		public virtual int? IdAplicacion
		{
			get
			{
				return this.IdAplicacion1;
			}
			set
			{
				this.IdAplicacion1 = value;
			}
		}
		
		private SSO_Role SSO_Role1;
		public virtual SSO_Role SSO_Role
		{
			get
			{
				return this.SSO_Role1;
			}
			set
			{
				this.SSO_Role1 = value;
			}
		}
		
		private SSO_Role SSO_Role21;
		public virtual SSO_Role SSO_Role2
		{
			get
			{
				return this.SSO_Role21;
			}
			set
			{
				this.SSO_Role21 = value;
			}
		}
		
		private SSO_Application SSO_Application1;
		public virtual SSO_Application SSO_Application
		{
			get
			{
				return this.SSO_Application1;
			}
			set
			{
				this.SSO_Application1 = value;
			}
		}
		
		private IList<SSO_RoleGroups_Member> SSO_RoleGroups_Members1 = new List<SSO_RoleGroups_Member>();
		public virtual IList<SSO_RoleGroups_Member> SSO_RoleGroups_Members
		{
			get
			{
				return this.SSO_RoleGroups_Members1;
			}
		}
		
	}
}
#pragma warning restore 1591
