#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class SSO_RoleGroups_Member
	{
		private int GroupId1;
		public virtual int GroupId
		{
			get
			{
				return this.GroupId1;
			}
			set
			{
				this.GroupId1 = value;
			}
		}
		
		private int RoleId1;
		public virtual int RoleId
		{
			get
			{
				return this.RoleId1;
			}
			set
			{
				this.RoleId1 = value;
			}
		}
		
		private int IdRoleGroupMember1;
		public virtual int IdRoleGroupMember
		{
			get
			{
				return this.IdRoleGroupMember1;
			}
			set
			{
				this.IdRoleGroupMember1 = value;
			}
		}
		
		private SSO_RoleGroup SSO_RoleGroup1;
		public virtual SSO_RoleGroup SSO_RoleGroup
		{
			get
			{
				return this.SSO_RoleGroup1;
			}
			set
			{
				this.SSO_RoleGroup1 = value;
			}
		}
		
		private SSO_Role SSO_Role1;
		public virtual SSO_Role SSO_Role
		{
			get
			{
				return this.SSO_Role1;
			}
			set
			{
				this.SSO_Role1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
