#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_StoredVariables_Template
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private string Description1;
		public virtual string Description
		{
			get
			{
				return this.Description1;
			}
			set
			{
				this.Description1 = value;
			}
		}
		
		private string Query1;
		public virtual string Query
		{
			get
			{
				return this.Query1;
			}
			set
			{
				this.Query1 = value;
			}
		}
		
		private bool MultipleValues1;
		public virtual bool MultipleValues
		{
			get
			{
				return this.MultipleValues1;
			}
			set
			{
				this.MultipleValues1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
