#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_Permission
	{
		private int SourceType1;
		public virtual int SourceType
		{
			get
			{
				return this.SourceType1;
			}
			set
			{
				this.SourceType1 = value;
			}
		}
		
		private int Source1;
		public virtual int Source
		{
			get
			{
				return this.Source1;
			}
			set
			{
				this.Source1 = value;
			}
		}
		
		private int TargetType1;
		public virtual int TargetType
		{
			get
			{
				return this.TargetType1;
			}
			set
			{
				this.TargetType1 = value;
			}
		}
		
		private int Target1;
		public virtual int Target
		{
			get
			{
				return this.Target1;
			}
			set
			{
				this.Target1 = value;
			}
		}
		
		private bool Allow1;
		public virtual bool Allow
		{
			get
			{
				return this.Allow1;
			}
			set
			{
				this.Allow1 = value;
			}
		}
		
		private bool Readonly1;
		public virtual bool Readonly
		{
			get
			{
				return this.Readonly1;
			}
			set
			{
				this.Readonly1 = value;
			}
		}
		
		private DateTime? EndDate1;
		public virtual DateTime? EndDate
		{
			get
			{
				return this.EndDate1;
			}
			set
			{
				this.EndDate1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
