#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class SSO_Users_Roles_Temp
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private int UserId1;
		public virtual int UserId
		{
			get
			{
				return this.UserId1;
			}
			set
			{
				this.UserId1 = value;
			}
		}
		
		private int RoleId1;
		public virtual int RoleId
		{
			get
			{
				return this.RoleId1;
			}
			set
			{
				this.RoleId1 = value;
			}
		}
		
		private string Comentario1;
		public virtual string Comentario
		{
			get
			{
				return this.Comentario1;
			}
			set
			{
				this.Comentario1 = value;
			}
		}
		
		private bool Procesado1;
		public virtual bool Procesado
		{
			get
			{
				return this.Procesado1;
			}
			set
			{
				this.Procesado1 = value;
			}
		}
		
		private SSO_Role SSO_Role1;
		public virtual SSO_Role SSO_Role
		{
			get
			{
				return this.SSO_Role1;
			}
			set
			{
				this.SSO_Role1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
