#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Dominio;

namespace Dominio	
{
	public partial class SSO_Role
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private int? Parent1;
		public virtual int? Parent
		{
			get
			{
				return this.Parent1;
			}
			set
			{
				this.Parent1 = value;
			}
		}
		
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private bool Enabled1;
		public virtual bool Enabled
		{
			get
			{
				return this.Enabled1;
			}
			set
			{
				this.Enabled1 = value;
			}
		}
		
		private SSO_Role SSO_Role11;
		public virtual SSO_Role SSO_Role1
		{
			get
			{
				return this.SSO_Role11;
			}
			set
			{
				this.SSO_Role11 = value;
			}
		}
		
		private IList<SSO_Role> SSO_Roles1 = new List<SSO_Role>();
		public virtual IList<SSO_Role> SSO_Roles
		{
			get
			{
				return this.SSO_Roles1;
			}
		}
		
		private IList<SSO_RoleGroups_Member> SSO_RoleGroups_Members1 = new List<SSO_RoleGroups_Member>();
		public virtual IList<SSO_RoleGroups_Member> SSO_RoleGroups_Members
		{
			get
			{
				return this.SSO_RoleGroups_Members1;
			}
		}
		
	}
}
#pragma warning restore 1591
