#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_AllowedAppsByEfectorCentralResultSet0
	{
		private string _efector;
		public virtual string Efector
		{
			get
			{
				return this._efector;
			}
			set
			{
				this._efector = value;
			}
		}
		
		private string _perfil;
		public virtual string Perfil
		{
			get
			{
				return this._perfil;
			}
			set
			{
				this._perfil = value;
			}
		}
		
	}
}
#pragma warning restore 1591
