#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_RoleGroup
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private bool AutomaticName1;
		public virtual bool AutomaticName
		{
			get
			{
				return this.AutomaticName1;
			}
			set
			{
				this.AutomaticName1 = value;
			}
		}
		
		private int? IdEfector1;
		public virtual int? IdEfector
		{
			get
			{
				return this.IdEfector1;
			}
			set
			{
				this.IdEfector1 = value;
			}
		}
		
		private int? IdPerfil1;
		public virtual int? IdPerfil
		{
			get
			{
				return this.IdPerfil1;
			}
			set
			{
				this.IdPerfil1 = value;
			}
		}
		
		private int? IdAplicacion1;
		public virtual int? IdAplicacion
		{
			get
			{
				return this.IdAplicacion1;
			}
			set
			{
				this.IdAplicacion1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
