#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_GetPermisosXUsuarioResultSet0
	{
		private int _sourceType;
		public virtual int sourceType
		{
			get
			{
				return this._sourceType;
			}
			set
			{
				this._sourceType = value;
			}
		}
		
		private int _source;
		public virtual int source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		
		private int _targetType;
		public virtual int targetType
		{
			get
			{
				return this._targetType;
			}
			set
			{
				this._targetType = value;
			}
		}
		
		private int _target;
		public virtual int target
		{
			get
			{
				return this._target;
			}
			set
			{
				this._target = value;
			}
		}
		
		private bool _allow;
		public virtual bool allow
		{
			get
			{
				return this._allow;
			}
			set
			{
				this._allow = value;
			}
		}
		
		private bool __readonly;
		public virtual bool _readonly
		{
			get
			{
				return this.__readonly;
			}
			set
			{
				this.__readonly = value;
			}
		}
		
		private DateTime? _endDate;
		public virtual DateTime? endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private int _id;
		public virtual int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _name;
		public virtual string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private bool _automaticName;
		public virtual bool automaticName
		{
			get
			{
				return this._automaticName;
			}
			set
			{
				this._automaticName = value;
			}
		}
		
		private int? _idEfector;
		public virtual int? idEfector
		{
			get
			{
				return this._idEfector;
			}
			set
			{
				this._idEfector = value;
			}
		}
		
		private int? _idPerfil;
		public virtual int? idPerfil
		{
			get
			{
				return this._idPerfil;
			}
			set
			{
				this._idPerfil = value;
			}
		}
		
		private int? _idAplicacion;
		public virtual int? idAplicacion
		{
			get
			{
				return this._idAplicacion;
			}
			set
			{
				this._idAplicacion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
