#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_Config
	{
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private int? ValueInt1;
		public virtual int? ValueInt
		{
			get
			{
				return this.ValueInt1;
			}
			set
			{
				this.ValueInt1 = value;
			}
		}
		
		private string ValueStr1;
		public virtual string ValueStr
		{
			get
			{
				return this.ValueStr1;
			}
			set
			{
				this.ValueStr1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
