#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_GetProfesionalesXGuardiaResultSet0
	{
		private int _idMedico;
		public virtual int idMedico
		{
			get
			{
				return this._idMedico;
			}
			set
			{
				this._idMedico = value;
			}
		}
		
		private string _idFuncion;
		public virtual string idFuncion
		{
			get
			{
				return this._idFuncion;
			}
			set
			{
				this._idFuncion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
