#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class SSO_User
	{
		private int Id1;
		public virtual int Id
		{
			get
			{
				return this.Id1;
			}
			set
			{
				this.Id1 = value;
			}
		}
		
		private string Username1;
		public virtual string Username
		{
			get
			{
				return this.Username1;
			}
			set
			{
				this.Username1 = value;
			}
		}
		
		private string Password1;
		public virtual string Password
		{
			get
			{
				return this.Password1;
			}
			set
			{
				this.Password1 = value;
			}
		}
		
		private string Name1;
		public virtual string Name
		{
			get
			{
				return this.Name1;
			}
			set
			{
				this.Name1 = value;
			}
		}
		
		private string Surname1;
		public virtual string Surname
		{
			get
			{
				return this.Surname1;
			}
			set
			{
				this.Surname1 = value;
			}
		}
		
		private bool Enabled1;
		public virtual bool Enabled
		{
			get
			{
				return this.Enabled1;
			}
			set
			{
				this.Enabled1 = value;
			}
		}
		
		private string Description1;
		public virtual string Description
		{
			get
			{
				return this.Description1;
			}
			set
			{
				this.Description1 = value;
			}
		}
		
		private string Email1;
		public virtual string Email
		{
			get
			{
				return this.Email1;
			}
			set
			{
				this.Email1 = value;
			}
		}
		
		private string Mobile1;
		public virtual string Mobile
		{
			get
			{
				return this.Mobile1;
			}
			set
			{
				this.Mobile1 = value;
			}
		}
		
		private string MobileCarrier1;
		public virtual string MobileCarrier
		{
			get
			{
				return this.MobileCarrier1;
			}
			set
			{
				this.MobileCarrier1 = value;
			}
		}
		
		private int? IdCarrier1;
		public virtual int? IdCarrier
		{
			get
			{
				return this.IdCarrier1;
			}
			set
			{
				this.IdCarrier1 = value;
			}
		}
		
		private Object External_id1;
		public virtual Object External_id
		{
			get
			{
				return this.External_id1;
			}
			set
			{
				this.External_id1 = value;
			}
		}
		
		private bool Locked1;
		public virtual bool Locked
		{
			get
			{
				return this.Locked1;
			}
			set
			{
				this.Locked1 = value;
			}
		}
		
		private DateTime? Locked_since1;
		public virtual DateTime? Locked_since
		{
			get
			{
				return this.Locked_since1;
			}
			set
			{
				this.Locked_since1 = value;
			}
		}
		
		private int Password_retry1;
		public virtual int Password_retry
		{
			get
			{
				return this.Password_retry1;
			}
			set
			{
				this.Password_retry1 = value;
			}
		}
		
		private bool Must_change_password1;
		public virtual bool Must_change_password
		{
			get
			{
				return this.Must_change_password1;
			}
			set
			{
				this.Must_change_password1 = value;
			}
		}
		
		private DateTime? Permissions_updatedOn1;
		public virtual DateTime? Permissions_updatedOn
		{
			get
			{
				return this.Permissions_updatedOn1;
			}
			set
			{
				this.Permissions_updatedOn1 = value;
			}
		}
		
		private int? Documento1;
		public virtual int? Documento
		{
			get
			{
				return this.Documento1;
			}
			set
			{
				this.Documento1 = value;
			}
		}
		
		private string Legajo1;
		public virtual string Legajo
		{
			get
			{
				return this.Legajo1;
			}
			set
			{
				this.Legajo1 = value;
			}
		}
		
		private string Observacion1;
		public virtual string Observacion
		{
			get
			{
				return this.Observacion1;
			}
			set
			{
				this.Observacion1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
