#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Dominio	
{
	public partial class Sys_Profesional
	{
		private int IdProfesional1;
		public virtual int IdProfesional
		{
			get
			{
				return this.IdProfesional1;
			}
			set
			{
				this.IdProfesional1 = value;
			}
		}
		
		private string Nombre1;
		public virtual string Nombre
		{
			get
			{
				return this.Nombre1;
			}
			set
			{
				this.Nombre1 = value;
			}
		}
		
		private string Apellido1;
		public virtual string Apellido
		{
			get
			{
				return this.Apellido1;
			}
			set
			{
				this.Apellido1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
